apiVersion: v1
kind: Service
metadata:
  name: text-service
  labels:
    app: text
spec:
  type: NodePort
  selector:
    app: text
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
